---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# changepoint.forecast

<!-- badges: start -->
<!-- badges: end -->

The goal of changepoint.forecast is to perform sequential changepoint analysis of forecast errors in order to quickly detect when forecasts become inaccurate. 

## Installation

<!-- You can install the released version of changepoint.forecast from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("changepoint.forecast")
```
-->
The development version can be downloaded from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("grundy95/changepoint.forecast")
```
<!-- ## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(changepoint.forecast)
## basic example code
```



You'll still need to render `README.Rmd` regularly, to keep `README.md` up-to-date. `devtools::build_readme()` is handy for this. You could also use GitHub Actions to re-render `README.Rmd` every time you push. An example workflow can be found here: <https://github.com/r-lib/actions/tree/master/examples>. -->


